language: go
install:
 - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update
 - sudo apt-get install qtdeclarative5-dev qtbase5-private-dev qtdeclarative5-private-dev libqt5opengl5-dev qtdeclarative5-qtquick2-plugin
go: 
 - 1.2
 - 1.3
 - release
 - tip
