// Code generated by protoc-gen-gogo.
// source: ClientServer.proto
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/gogoprotobuf/proto"
import math "math"

// discarding unused import gogoproto "github.com/gogo/protobuf/gogoproto/gogo.pb"

import io1 "io"
import fmt1 "fmt"
import code_google_com_p_gogoprotobuf_proto1 "code.google.com/p/gogoprotobuf/proto"

import bytes1 "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type ServerToClient_StatusCode int32

const (
	ServerToClient_OK          ServerToClient_StatusCode = 0
	ServerToClient_PARSE_ERROR ServerToClient_StatusCode = 1
)

var ServerToClient_StatusCode_name = map[int32]string{
	0: "OK",
	1: "PARSE_ERROR",
}
var ServerToClient_StatusCode_value = map[string]int32{
	"OK":          0,
	"PARSE_ERROR": 1,
}

func (x ServerToClient_StatusCode) Enum() *ServerToClient_StatusCode {
	p := new(ServerToClient_StatusCode)
	*p = x
	return p
}
func (x ServerToClient_StatusCode) String() string {
	return proto1.EnumName(ServerToClient_StatusCode_name, int32(x))
}
func (x *ServerToClient_StatusCode) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(ServerToClient_StatusCode_value, data, "ServerToClient_StatusCode")
	if err != nil {
		return err
	}
	*x = ServerToClient_StatusCode(value)
	return nil
}

type ServerToClient struct {
	Status           *ServerToClient_StatusCode `protobuf:"varint,1,req,name=status,enum=proto.ServerToClient_StatusCode" json:"status,omitempty"`
	MessageList      []Byte32                   `protobuf:"bytes,3,rep,name=message_list,customtype=Byte32" json:"message_list,omitempty"`
	Envelope         []byte                     `protobuf:"bytes,4,opt,name=envelope" json:"envelope,omitempty"`
	SignedKey        []byte                     `protobuf:"bytes,5,opt,name=signed_key" json:"signed_key,omitempty"`
	Notification     []byte                     `protobuf:"bytes,6,opt,name=notification" json:"notification,omitempty"`
	NumKeys          *int64                     `protobuf:"varint,7,opt,name=num_keys" json:"num_keys,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ServerToClient) Reset()         { *m = ServerToClient{} }
func (m *ServerToClient) String() string { return proto1.CompactTextString(m) }
func (*ServerToClient) ProtoMessage()    {}

type ClientToServer struct {
	CreateAccount    *bool                           `protobuf:"varint,1,opt,name=create_account" json:"create_account,omitempty"`
	DeliverEnvelope  *ClientToServer_DeliverEnvelope `protobuf:"bytes,2,opt,name=deliver_envelope" json:"deliver_envelope,omitempty"`
	DownloadEnvelope *Byte32                         `protobuf:"bytes,6,opt,name=download_envelope,customtype=Byte32" json:"download_envelope,omitempty"`
	ListMessages     *bool                           `protobuf:"varint,5,opt,name=list_messages" json:"list_messages,omitempty"`
	DeleteMessages   []Byte32                        `protobuf:"bytes,7,rep,name=delete_messages,customtype=Byte32" json:"delete_messages,omitempty"`
	UploadSignedKeys [][]byte                        `protobuf:"bytes,8,rep,name=upload_signed_keys" json:"upload_signed_keys,omitempty"`
	GetSignedKey     *Byte32                         `protobuf:"bytes,9,opt,name=get_signed_key,customtype=Byte32" json:"get_signed_key,omitempty"`
	ReceiveEnvelopes *bool                           `protobuf:"varint,10,opt,name=receive_envelopes" json:"receive_envelopes,omitempty"`
	GetNumKeys       *bool                           `protobuf:"varint,11,opt,name=get_num_keys" json:"get_num_keys,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *ClientToServer) Reset()         { *m = ClientToServer{} }
func (m *ClientToServer) String() string { return proto1.CompactTextString(m) }
func (*ClientToServer) ProtoMessage()    {}

type ClientToServer_DeliverEnvelope struct {
	User             *Byte32 `protobuf:"bytes,3,req,customtype=Byte32" json:"User,omitempty"`
	Envelope         []byte  `protobuf:"bytes,4,req" json:"Envelope,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ClientToServer_DeliverEnvelope) Reset()         { *m = ClientToServer_DeliverEnvelope{} }
func (m *ClientToServer_DeliverEnvelope) String() string { return proto1.CompactTextString(m) }
func (*ClientToServer_DeliverEnvelope) ProtoMessage()    {}

func init() {
	proto1.RegisterEnum("proto.ServerToClient_StatusCode", ServerToClient_StatusCode_name, ServerToClient_StatusCode_value)
}
func (m *ServerToClient) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io1.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt1.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var v ServerToClient_StatusCode
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				v |= (ServerToClient_StatusCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Status = &v
		case 3:
			if wireType != 2 {
				return fmt1.Errorf("proto: wrong wireType = %d for field MessageList", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io1.ErrUnexpectedEOF
			}
			m.MessageList = append(m.MessageList, Byte32{})
			m.MessageList[len(m.MessageList)-1].Unmarshal(data[index:postIndex])
			index = postIndex
		case 4:
			if wireType != 2 {
				return fmt1.Errorf("proto: wrong wireType = %d for field Envelope", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io1.ErrUnexpectedEOF
			}
			m.Envelope = append(m.Envelope, data[index:postIndex]...)
			index = postIndex
		case 5:
			if wireType != 2 {
				return fmt1.Errorf("proto: wrong wireType = %d for field SignedKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io1.ErrUnexpectedEOF
			}
			m.SignedKey = append(m.SignedKey, data[index:postIndex]...)
			index = postIndex
		case 6:
			if wireType != 2 {
				return fmt1.Errorf("proto: wrong wireType = %d for field Notification", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io1.ErrUnexpectedEOF
			}
			m.Notification = append(m.Notification, data[index:postIndex]...)
			index = postIndex
		case 7:
			if wireType != 0 {
				return fmt1.Errorf("proto: wrong wireType = %d for field NumKeys", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				v |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NumKeys = &v
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto1.Skip(data[index:])
			if err != nil {
				return err
			}
			if (index + skippy) > l {
				return io1.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *ClientToServer) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io1.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt1.Errorf("proto: wrong wireType = %d for field CreateAccount", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.CreateAccount = &b
		case 2:
			if wireType != 2 {
				return fmt1.Errorf("proto: wrong wireType = %d for field DeliverEnvelope", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + msglen
			if postIndex > l {
				return io1.ErrUnexpectedEOF
			}
			if m.DeliverEnvelope == nil {
				m.DeliverEnvelope = &ClientToServer_DeliverEnvelope{}
			}
			if err := m.DeliverEnvelope.Unmarshal(data[index:postIndex]); err != nil {
				return err
			}
			index = postIndex
		case 6:
			if wireType != 2 {
				return fmt1.Errorf("proto: wrong wireType = %d for field DownloadEnvelope", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io1.ErrUnexpectedEOF
			}
			m.DownloadEnvelope = &Byte32{}
			if err := m.DownloadEnvelope.Unmarshal(data[index:postIndex]); err != nil {
				return err
			}
			index = postIndex
		case 5:
			if wireType != 0 {
				return fmt1.Errorf("proto: wrong wireType = %d for field ListMessages", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.ListMessages = &b
		case 7:
			if wireType != 2 {
				return fmt1.Errorf("proto: wrong wireType = %d for field DeleteMessages", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io1.ErrUnexpectedEOF
			}
			m.DeleteMessages = append(m.DeleteMessages, Byte32{})
			m.DeleteMessages[len(m.DeleteMessages)-1].Unmarshal(data[index:postIndex])
			index = postIndex
		case 8:
			if wireType != 2 {
				return fmt1.Errorf("proto: wrong wireType = %d for field UploadSignedKeys", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io1.ErrUnexpectedEOF
			}
			m.UploadSignedKeys = append(m.UploadSignedKeys, make([]byte, postIndex-index))
			copy(m.UploadSignedKeys[len(m.UploadSignedKeys)-1], data[index:postIndex])
			index = postIndex
		case 9:
			if wireType != 2 {
				return fmt1.Errorf("proto: wrong wireType = %d for field GetSignedKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io1.ErrUnexpectedEOF
			}
			m.GetSignedKey = &Byte32{}
			if err := m.GetSignedKey.Unmarshal(data[index:postIndex]); err != nil {
				return err
			}
			index = postIndex
		case 10:
			if wireType != 0 {
				return fmt1.Errorf("proto: wrong wireType = %d for field ReceiveEnvelopes", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.ReceiveEnvelopes = &b
		case 11:
			if wireType != 0 {
				return fmt1.Errorf("proto: wrong wireType = %d for field GetNumKeys", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.GetNumKeys = &b
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto1.Skip(data[index:])
			if err != nil {
				return err
			}
			if (index + skippy) > l {
				return io1.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *ClientToServer_DeliverEnvelope) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io1.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 3:
			if wireType != 2 {
				return fmt1.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io1.ErrUnexpectedEOF
			}
			m.User = &Byte32{}
			if err := m.User.Unmarshal(data[index:postIndex]); err != nil {
				return err
			}
			index = postIndex
		case 4:
			if wireType != 2 {
				return fmt1.Errorf("proto: wrong wireType = %d for field Envelope", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io1.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io1.ErrUnexpectedEOF
			}
			m.Envelope = append(m.Envelope, data[index:postIndex]...)
			index = postIndex
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto1.Skip(data[index:])
			if err != nil {
				return err
			}
			if (index + skippy) > l {
				return io1.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *ServerToClient) Size() (n int) {
	var l int
	_ = l
	if m.Status != nil {
		n += 1 + sovClientServer(uint64(*m.Status))
	}
	if len(m.MessageList) > 0 {
		for _, e := range m.MessageList {
			l = e.Size()
			n += 1 + l + sovClientServer(uint64(l))
		}
	}
	if m.Envelope != nil {
		l = len(m.Envelope)
		n += 1 + l + sovClientServer(uint64(l))
	}
	if m.SignedKey != nil {
		l = len(m.SignedKey)
		n += 1 + l + sovClientServer(uint64(l))
	}
	if m.Notification != nil {
		l = len(m.Notification)
		n += 1 + l + sovClientServer(uint64(l))
	}
	if m.NumKeys != nil {
		n += 1 + sovClientServer(uint64(*m.NumKeys))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *ClientToServer) Size() (n int) {
	var l int
	_ = l
	if m.CreateAccount != nil {
		n += 2
	}
	if m.DeliverEnvelope != nil {
		l = m.DeliverEnvelope.Size()
		n += 1 + l + sovClientServer(uint64(l))
	}
	if m.DownloadEnvelope != nil {
		l = m.DownloadEnvelope.Size()
		n += 1 + l + sovClientServer(uint64(l))
	}
	if m.ListMessages != nil {
		n += 2
	}
	if len(m.DeleteMessages) > 0 {
		for _, e := range m.DeleteMessages {
			l = e.Size()
			n += 1 + l + sovClientServer(uint64(l))
		}
	}
	if len(m.UploadSignedKeys) > 0 {
		for _, b := range m.UploadSignedKeys {
			l = len(b)
			n += 1 + l + sovClientServer(uint64(l))
		}
	}
	if m.GetSignedKey != nil {
		l = m.GetSignedKey.Size()
		n += 1 + l + sovClientServer(uint64(l))
	}
	if m.ReceiveEnvelopes != nil {
		n += 2
	}
	if m.GetNumKeys != nil {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *ClientToServer_DeliverEnvelope) Size() (n int) {
	var l int
	_ = l
	if m.User != nil {
		l = m.User.Size()
		n += 1 + l + sovClientServer(uint64(l))
	}
	if m.Envelope != nil {
		l = len(m.Envelope)
		n += 1 + l + sovClientServer(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovClientServer(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozClientServer(x uint64) (n int) {
	return sovClientServer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func NewPopulatedServerToClient(r randyClientServer, easy bool) *ServerToClient {
	this := &ServerToClient{}
	v1 := ServerToClient_StatusCode([]int32{0, 1}[r.Intn(2)])
	this.Status = &v1
	if r.Intn(10) != 0 {
		v2 := r.Intn(10)
		this.MessageList = make([]Byte32, v2)
		for i := 0; i < v2; i++ {
			v3 := NewPopulatedByte32(r)
			this.MessageList[i] = *v3
		}
	}
	if r.Intn(10) != 0 {
		v4 := r.Intn(100)
		this.Envelope = make([]byte, v4)
		for i := 0; i < v4; i++ {
			this.Envelope[i] = byte(r.Intn(256))
		}
	}
	if r.Intn(10) != 0 {
		v5 := r.Intn(100)
		this.SignedKey = make([]byte, v5)
		for i := 0; i < v5; i++ {
			this.SignedKey[i] = byte(r.Intn(256))
		}
	}
	if r.Intn(10) != 0 {
		v6 := r.Intn(100)
		this.Notification = make([]byte, v6)
		for i := 0; i < v6; i++ {
			this.Notification[i] = byte(r.Intn(256))
		}
	}
	if r.Intn(10) != 0 {
		v7 := r.Int63()
		if r.Intn(2) == 0 {
			v7 *= -1
		}
		this.NumKeys = &v7
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedClientServer(r, 8)
	}
	return this
}

func NewPopulatedClientToServer(r randyClientServer, easy bool) *ClientToServer {
	this := &ClientToServer{}
	if r.Intn(10) != 0 {
		v8 := bool(r.Intn(2) == 0)
		this.CreateAccount = &v8
	}
	if r.Intn(10) != 0 {
		this.DeliverEnvelope = NewPopulatedClientToServer_DeliverEnvelope(r, easy)
	}
	if r.Intn(10) != 0 {
		this.DownloadEnvelope = NewPopulatedByte32(r)
	}
	if r.Intn(10) != 0 {
		v9 := bool(r.Intn(2) == 0)
		this.ListMessages = &v9
	}
	if r.Intn(10) != 0 {
		v10 := r.Intn(10)
		this.DeleteMessages = make([]Byte32, v10)
		for i := 0; i < v10; i++ {
			v11 := NewPopulatedByte32(r)
			this.DeleteMessages[i] = *v11
		}
	}
	if r.Intn(10) != 0 {
		v12 := r.Intn(100)
		this.UploadSignedKeys = make([][]byte, v12)
		for i := 0; i < v12; i++ {
			v13 := r.Intn(100)
			this.UploadSignedKeys[i] = make([]byte, v13)
			for j := 0; j < v13; j++ {
				this.UploadSignedKeys[i][j] = byte(r.Intn(256))
			}
		}
	}
	if r.Intn(10) != 0 {
		this.GetSignedKey = NewPopulatedByte32(r)
	}
	if r.Intn(10) != 0 {
		v14 := bool(r.Intn(2) == 0)
		this.ReceiveEnvelopes = &v14
	}
	if r.Intn(10) != 0 {
		v15 := bool(r.Intn(2) == 0)
		this.GetNumKeys = &v15
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedClientServer(r, 12)
	}
	return this
}

func NewPopulatedClientToServer_DeliverEnvelope(r randyClientServer, easy bool) *ClientToServer_DeliverEnvelope {
	this := &ClientToServer_DeliverEnvelope{}
	this.User = NewPopulatedByte32(r)
	v16 := r.Intn(100)
	this.Envelope = make([]byte, v16)
	for i := 0; i < v16; i++ {
		this.Envelope[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedClientServer(r, 5)
	}
	return this
}

type randyClientServer interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneClientServer(r randyClientServer) rune {
	res := rune(r.Uint32() % 1112064)
	if 55296 <= res {
		res += 2047
	}
	return res
}
func randStringClientServer(r randyClientServer) string {
	v17 := r.Intn(100)
	tmps := make([]rune, v17)
	for i := 0; i < v17; i++ {
		tmps[i] = randUTF8RuneClientServer(r)
	}
	return string(tmps)
}
func randUnrecognizedClientServer(r randyClientServer, maxFieldNumber int) (data []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		data = randFieldClientServer(data, r, fieldNumber, wire)
	}
	return data
}
func randFieldClientServer(data []byte, r randyClientServer, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		data = encodeVarintPopulateClientServer(data, uint64(key))
		v18 := r.Int63()
		if r.Intn(2) == 0 {
			v18 *= -1
		}
		data = encodeVarintPopulateClientServer(data, uint64(v18))
	case 1:
		data = encodeVarintPopulateClientServer(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		data = encodeVarintPopulateClientServer(data, uint64(key))
		ll := r.Intn(100)
		data = encodeVarintPopulateClientServer(data, uint64(ll))
		for j := 0; j < ll; j++ {
			data = append(data, byte(r.Intn(256)))
		}
	default:
		data = encodeVarintPopulateClientServer(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return data
}
func encodeVarintPopulateClientServer(data []byte, v uint64) []byte {
	for v >= 1<<7 {
		data = append(data, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	data = append(data, uint8(v))
	return data
}
func (m *ServerToClient) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *ServerToClient) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status != nil {
		data[i] = 0x8
		i++
		i = encodeVarintClientServer(data, i, uint64(*m.Status))
	}
	if len(m.MessageList) > 0 {
		for _, msg := range m.MessageList {
			data[i] = 0x1a
			i++
			i = encodeVarintClientServer(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Envelope != nil {
		data[i] = 0x22
		i++
		i = encodeVarintClientServer(data, i, uint64(len(m.Envelope)))
		i += copy(data[i:], m.Envelope)
	}
	if m.SignedKey != nil {
		data[i] = 0x2a
		i++
		i = encodeVarintClientServer(data, i, uint64(len(m.SignedKey)))
		i += copy(data[i:], m.SignedKey)
	}
	if m.Notification != nil {
		data[i] = 0x32
		i++
		i = encodeVarintClientServer(data, i, uint64(len(m.Notification)))
		i += copy(data[i:], m.Notification)
	}
	if m.NumKeys != nil {
		data[i] = 0x38
		i++
		i = encodeVarintClientServer(data, i, uint64(*m.NumKeys))
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *ClientToServer) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *ClientToServer) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.CreateAccount != nil {
		data[i] = 0x8
		i++
		if *m.CreateAccount {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.DeliverEnvelope != nil {
		data[i] = 0x12
		i++
		i = encodeVarintClientServer(data, i, uint64(m.DeliverEnvelope.Size()))
		n1, err := m.DeliverEnvelope.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.DownloadEnvelope != nil {
		data[i] = 0x32
		i++
		i = encodeVarintClientServer(data, i, uint64(m.DownloadEnvelope.Size()))
		n2, err := m.DownloadEnvelope.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.ListMessages != nil {
		data[i] = 0x28
		i++
		if *m.ListMessages {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if len(m.DeleteMessages) > 0 {
		for _, msg := range m.DeleteMessages {
			data[i] = 0x3a
			i++
			i = encodeVarintClientServer(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.UploadSignedKeys) > 0 {
		for _, b := range m.UploadSignedKeys {
			data[i] = 0x42
			i++
			i = encodeVarintClientServer(data, i, uint64(len(b)))
			i += copy(data[i:], b)
		}
	}
	if m.GetSignedKey != nil {
		data[i] = 0x4a
		i++
		i = encodeVarintClientServer(data, i, uint64(m.GetSignedKey.Size()))
		n3, err := m.GetSignedKey.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.ReceiveEnvelopes != nil {
		data[i] = 0x50
		i++
		if *m.ReceiveEnvelopes {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.GetNumKeys != nil {
		data[i] = 0x58
		i++
		if *m.GetNumKeys {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *ClientToServer_DeliverEnvelope) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *ClientToServer_DeliverEnvelope) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.User != nil {
		data[i] = 0x1a
		i++
		i = encodeVarintClientServer(data, i, uint64(m.User.Size()))
		n4, err := m.User.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.Envelope != nil {
		data[i] = 0x22
		i++
		i = encodeVarintClientServer(data, i, uint64(len(m.Envelope)))
		i += copy(data[i:], m.Envelope)
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func encodeFixed64ClientServer(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32ClientServer(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintClientServer(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (this *ServerToClient) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*ServerToClient)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Status != nil && that1.Status != nil {
		if *this.Status != *that1.Status {
			return false
		}
	} else if this.Status != nil {
		return false
	} else if that1.Status != nil {
		return false
	}
	if len(this.MessageList) != len(that1.MessageList) {
		return false
	}
	for i := range this.MessageList {
		if !this.MessageList[i].Equal(that1.MessageList[i]) {
			return false
		}
	}
	if !bytes1.Equal(this.Envelope, that1.Envelope) {
		return false
	}
	if !bytes1.Equal(this.SignedKey, that1.SignedKey) {
		return false
	}
	if !bytes1.Equal(this.Notification, that1.Notification) {
		return false
	}
	if this.NumKeys != nil && that1.NumKeys != nil {
		if *this.NumKeys != *that1.NumKeys {
			return false
		}
	} else if this.NumKeys != nil {
		return false
	} else if that1.NumKeys != nil {
		return false
	}
	if !bytes1.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ClientToServer) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*ClientToServer)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.CreateAccount != nil && that1.CreateAccount != nil {
		if *this.CreateAccount != *that1.CreateAccount {
			return false
		}
	} else if this.CreateAccount != nil {
		return false
	} else if that1.CreateAccount != nil {
		return false
	}
	if !this.DeliverEnvelope.Equal(that1.DeliverEnvelope) {
		return false
	}
	if that1.DownloadEnvelope == nil {
		if this.DownloadEnvelope != nil {
			return false
		}
	} else if !this.DownloadEnvelope.Equal(*that1.DownloadEnvelope) {
		return false
	}
	if this.ListMessages != nil && that1.ListMessages != nil {
		if *this.ListMessages != *that1.ListMessages {
			return false
		}
	} else if this.ListMessages != nil {
		return false
	} else if that1.ListMessages != nil {
		return false
	}
	if len(this.DeleteMessages) != len(that1.DeleteMessages) {
		return false
	}
	for i := range this.DeleteMessages {
		if !this.DeleteMessages[i].Equal(that1.DeleteMessages[i]) {
			return false
		}
	}
	if len(this.UploadSignedKeys) != len(that1.UploadSignedKeys) {
		return false
	}
	for i := range this.UploadSignedKeys {
		if !bytes1.Equal(this.UploadSignedKeys[i], that1.UploadSignedKeys[i]) {
			return false
		}
	}
	if that1.GetSignedKey == nil {
		if this.GetSignedKey != nil {
			return false
		}
	} else if !this.GetSignedKey.Equal(*that1.GetSignedKey) {
		return false
	}
	if this.ReceiveEnvelopes != nil && that1.ReceiveEnvelopes != nil {
		if *this.ReceiveEnvelopes != *that1.ReceiveEnvelopes {
			return false
		}
	} else if this.ReceiveEnvelopes != nil {
		return false
	} else if that1.ReceiveEnvelopes != nil {
		return false
	}
	if this.GetNumKeys != nil && that1.GetNumKeys != nil {
		if *this.GetNumKeys != *that1.GetNumKeys {
			return false
		}
	} else if this.GetNumKeys != nil {
		return false
	} else if that1.GetNumKeys != nil {
		return false
	}
	if !bytes1.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ClientToServer_DeliverEnvelope) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*ClientToServer_DeliverEnvelope)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if that1.User == nil {
		if this.User != nil {
			return false
		}
	} else if !this.User.Equal(*that1.User) {
		return false
	}
	if !bytes1.Equal(this.Envelope, that1.Envelope) {
		return false
	}
	if !bytes1.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
