// Code generated by protoc-gen-gogo.
// source: ConversationMetadata.proto
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/gogoprotobuf/proto"
import math "math"

// discarding unused import gogoproto "code.google.com/p/gogoprotobuf/gogoproto/gogo.pb"

import github_com_andres_erbsen_dename_protocol "github.com/andres-erbsen/dename/protocol"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type ConversationMetadata struct {
	Participants        []string                                         `protobuf:"bytes,1,rep,name=participants" json:"participants"`
	Subject             string                                           `protobuf:"bytes,2,req,name=subject" json:"subject"`
	SenderDenameProfile github_com_andres_erbsen_dename_protocol.Profile `protobuf:"bytes,3,req,name=sender_dename_profile,customtype=github.com/andres-erbsen/dename/protocol.Profile" json:"sender_dename_profile"`
	XXX_unrecognized    []byte                                           `json:"-"`
}

func (m *ConversationMetadata) Reset()         { *m = ConversationMetadata{} }
func (m *ConversationMetadata) String() string { return proto1.CompactTextString(m) }
func (*ConversationMetadata) ProtoMessage()    {}

func init() {
}
