// Code generated by protoc-gen-gogo.
// source: Messages.proto
// DO NOT EDIT!

/*
Package Messages is a generated protocol buffer package.

It is generated from these files:
	Messages.proto

It has these top-level messages:
	ServerToClient
	ClientToServer
*/
package Messages

import proto "code.google.com/p/gogoprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ServerToClient_StatusCode int32

const (
	ServerToClient_OK          ServerToClient_StatusCode = 0
	ServerToClient_PARSE_ERROR ServerToClient_StatusCode = 1
)

var ServerToClient_StatusCode_name = map[int32]string{
	0: "OK",
	1: "PARSE_ERROR",
}
var ServerToClient_StatusCode_value = map[string]int32{
	"OK":          0,
	"PARSE_ERROR": 1,
}

func (x ServerToClient_StatusCode) Enum() *ServerToClient_StatusCode {
	p := new(ServerToClient_StatusCode)
	*p = x
	return p
}
func (x ServerToClient_StatusCode) String() string {
	return proto.EnumName(ServerToClient_StatusCode_name, int32(x))
}
func (x *ServerToClient_StatusCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerToClient_StatusCode_value, data, "ServerToClient_StatusCode")
	if err != nil {
		return err
	}
	*x = ServerToClient_StatusCode(value)
	return nil
}

type ServerToClient struct {
	Status           *ServerToClient_StatusCode `protobuf:"varint,1,req,name=status,enum=ServerToClient_StatusCode" json:"status,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ServerToClient) Reset()         { *m = ServerToClient{} }
func (m *ServerToClient) String() string { return proto.CompactTextString(m) }
func (*ServerToClient) ProtoMessage()    {}

func (m *ServerToClient) GetStatus() ServerToClient_StatusCode {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ServerToClient_OK
}

type ClientToServer struct {
	CreateAccount    *bool  `protobuf:"varint,1,opt,name=create_account" json:"create_account,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ClientToServer) Reset()         { *m = ClientToServer{} }
func (m *ClientToServer) String() string { return proto.CompactTextString(m) }
func (*ClientToServer) ProtoMessage()    {}

func (m *ClientToServer) GetCreateAccount() bool {
	if m != nil && m.CreateAccount != nil {
		return *m.CreateAccount
	}
	return false
}

func init() {
	proto.RegisterEnum("ServerToClient_StatusCode", ServerToClient_StatusCode_name, ServerToClient_StatusCode_value)
}
