// Code generated by protoc-gen-gogo.
// source: MessagePayload.proto
// DO NOT EDIT!

package proto

import testing20 "testing"
import math_rand20 "math/rand"
import time20 "time"
import github_com_gogo_protobuf_proto15 "github.com/gogo/protobuf/proto"
import testing21 "testing"
import math_rand21 "math/rand"
import time21 "time"
import encoding_json5 "encoding/json"
import testing22 "testing"
import math_rand22 "math/rand"
import time22 "time"
import github_com_gogo_protobuf_proto16 "github.com/gogo/protobuf/proto"
import math_rand23 "math/rand"
import time23 "time"
import testing23 "testing"
import github_com_gogo_protobuf_proto17 "github.com/gogo/protobuf/proto"

func TestMessagePayloadProto(t *testing20.T) {
	popr := math_rand20.New(math_rand20.NewSource(time20.Now().UnixNano()))
	p := NewPopulatedMessagePayload(popr, false)
	data, err := github_com_gogo_protobuf_proto15.Marshal(p)
	if err != nil {
		panic(err)
	}
	msg := &MessagePayload{}
	if err := github_com_gogo_protobuf_proto15.Unmarshal(data, msg); err != nil {
		panic(err)
	}
	for i := range data {
		data[i] = byte(popr.Intn(256))
	}
	if !p.Equal(msg) {
		t.Fatalf("%#v !Proto %#v", msg, p)
	}
}

func TestMessagePayloadMarshalTo(t *testing20.T) {
	popr := math_rand20.New(math_rand20.NewSource(time20.Now().UnixNano()))
	p := NewPopulatedMessagePayload(popr, false)
	size := p.Size()
	data := make([]byte, size)
	for i := range data {
		data[i] = byte(popr.Intn(256))
	}
	_, err := p.MarshalTo(data)
	if err != nil {
		panic(err)
	}
	msg := &MessagePayload{}
	if err := github_com_gogo_protobuf_proto15.Unmarshal(data, msg); err != nil {
		panic(err)
	}
	for i := range data {
		data[i] = byte(popr.Intn(256))
	}
	if !p.Equal(msg) {
		t.Fatalf("%#v !Proto %#v", msg, p)
	}
}

func BenchmarkMessagePayloadProtoMarshal(b *testing20.B) {
	popr := math_rand20.New(math_rand20.NewSource(616))
	total := 0
	pops := make([]*MessagePayload, 10000)
	for i := 0; i < 10000; i++ {
		pops[i] = NewPopulatedMessagePayload(popr, false)
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		data, err := github_com_gogo_protobuf_proto15.Marshal(pops[i%10000])
		if err != nil {
			panic(err)
		}
		total += len(data)
	}
	b.SetBytes(int64(total / b.N))
}

func BenchmarkMessagePayloadProtoUnmarshal(b *testing20.B) {
	popr := math_rand20.New(math_rand20.NewSource(616))
	total := 0
	datas := make([][]byte, 10000)
	for i := 0; i < 10000; i++ {
		data, err := github_com_gogo_protobuf_proto15.Marshal(NewPopulatedMessagePayload(popr, false))
		if err != nil {
			panic(err)
		}
		datas[i] = data
	}
	msg := &MessagePayload{}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		total += len(datas[i%10000])
		if err := github_com_gogo_protobuf_proto15.Unmarshal(datas[i%10000], msg); err != nil {
			panic(err)
		}
	}
	b.SetBytes(int64(total / b.N))
}

func TestMessagePayloadJSON(t *testing21.T) {
	popr := math_rand21.New(math_rand21.NewSource(time21.Now().UnixNano()))
	p := NewPopulatedMessagePayload(popr, true)
	jsondata, err := encoding_json5.Marshal(p)
	if err != nil {
		panic(err)
	}
	msg := &MessagePayload{}
	err = encoding_json5.Unmarshal(jsondata, msg)
	if err != nil {
		panic(err)
	}
	if !p.Equal(msg) {
		t.Fatalf("%#v !Json Equal %#v", msg, p)
	}
}
func TestMessagePayloadProtoText(t *testing22.T) {
	popr := math_rand22.New(math_rand22.NewSource(time22.Now().UnixNano()))
	p := NewPopulatedMessagePayload(popr, true)
	data := github_com_gogo_protobuf_proto16.MarshalTextString(p)
	msg := &MessagePayload{}
	if err := github_com_gogo_protobuf_proto16.UnmarshalText(data, msg); err != nil {
		panic(err)
	}
	if !p.Equal(msg) {
		t.Fatalf("%#v !Proto %#v", msg, p)
	}
}

func TestMessagePayloadProtoCompactText(t *testing22.T) {
	popr := math_rand22.New(math_rand22.NewSource(time22.Now().UnixNano()))
	p := NewPopulatedMessagePayload(popr, true)
	data := github_com_gogo_protobuf_proto16.CompactTextString(p)
	msg := &MessagePayload{}
	if err := github_com_gogo_protobuf_proto16.UnmarshalText(data, msg); err != nil {
		panic(err)
	}
	if !p.Equal(msg) {
		t.Fatalf("%#v !Proto %#v", msg, p)
	}
}

func TestMessagePayloadSize(t *testing23.T) {
	popr := math_rand23.New(math_rand23.NewSource(time23.Now().UnixNano()))
	p := NewPopulatedMessagePayload(popr, true)
	size2 := github_com_gogo_protobuf_proto17.Size(p)
	data, err := github_com_gogo_protobuf_proto17.Marshal(p)
	if err != nil {
		panic(err)
	}
	size := p.Size()
	if len(data) != size {
		t.Fatalf("size %v != marshalled size %v", size, len(data))
	}
	if size2 != size {
		t.Fatalf("size %v != before marshal proto.Size %v", size, size2)
	}
	size3 := github_com_gogo_protobuf_proto17.Size(p)
	if size3 != size {
		t.Fatalf("size %v != after marshal proto.Size %v", size, size3)
	}
}

func BenchmarkMessagePayloadSize(b *testing23.B) {
	popr := math_rand23.New(math_rand23.NewSource(616))
	total := 0
	pops := make([]*MessagePayload, 1000)
	for i := 0; i < 1000; i++ {
		pops[i] = NewPopulatedMessagePayload(popr, false)
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		total += pops[i%1000].Size()
	}
	b.SetBytes(int64(total / b.N))
}

//These tests are generated by github.com/gogo/protobuf/plugin/testgen
