// Code generated by protoc-gen-gogo.
// source: Messages.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	Messages.proto

It has these top-level messages:
	ServerToClient
	ClientToServer
*/
package proto

import proto1 "code.google.com/p/gogoprotobuf/proto"
import math "math"

// discarding unused import gogoproto "code.google.com/p/gogoprotobuf/gogoproto/gogo.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type ServerToClient_StatusCode int32

const (
	ServerToClient_OK          ServerToClient_StatusCode = 0
	ServerToClient_PARSE_ERROR ServerToClient_StatusCode = 1
)

var ServerToClient_StatusCode_name = map[int32]string{
	0: "OK",
	1: "PARSE_ERROR",
}
var ServerToClient_StatusCode_value = map[string]int32{
	"OK":          0,
	"PARSE_ERROR": 1,
}

func (x ServerToClient_StatusCode) Enum() *ServerToClient_StatusCode {
	p := new(ServerToClient_StatusCode)
	*p = x
	return p
}
func (x ServerToClient_StatusCode) String() string {
	return proto1.EnumName(ServerToClient_StatusCode_name, int32(x))
}
func (x *ServerToClient_StatusCode) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(ServerToClient_StatusCode_value, data, "ServerToClient_StatusCode")
	if err != nil {
		return err
	}
	*x = ServerToClient_StatusCode(value)
	return nil
}

type ServerToClient struct {
	Status           *ServerToClient_StatusCode `protobuf:"varint,1,req,name=status,enum=proto.ServerToClient_StatusCode" json:"status,omitempty"`
	MessageList      [][]byte                   `protobuf:"bytes,3,rep,name=message_list" json:"message_list"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ServerToClient) Reset()         { *m = ServerToClient{} }
func (m *ServerToClient) String() string { return proto1.CompactTextString(m) }
func (*ServerToClient) ProtoMessage()    {}

func (m *ServerToClient) GetStatus() ServerToClient_StatusCode {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ServerToClient_OK
}

func (m *ServerToClient) GetMessageList() [][]byte {
	if m != nil {
		return m.MessageList
	}
	return nil
}

type ClientToServer struct {
	CreateAccount    *bool                           `protobuf:"varint,1,opt,name=create_account" json:"create_account,omitempty"`
	DeliverEnvelope  *ClientToServer_DeliverEnvelope `protobuf:"bytes,2,opt,name=deliver_envelope" json:"deliver_envelope,omitempty"`
	ListMessages     *bool                           `protobuf:"varint,5,opt,name=list_messages" json:"list_messages,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *ClientToServer) Reset()         { *m = ClientToServer{} }
func (m *ClientToServer) String() string { return proto1.CompactTextString(m) }
func (*ClientToServer) ProtoMessage()    {}

func (m *ClientToServer) GetCreateAccount() bool {
	if m != nil && m.CreateAccount != nil {
		return *m.CreateAccount
	}
	return false
}

func (m *ClientToServer) GetDeliverEnvelope() *ClientToServer_DeliverEnvelope {
	if m != nil {
		return m.DeliverEnvelope
	}
	return nil
}

func (m *ClientToServer) GetListMessages() bool {
	if m != nil && m.ListMessages != nil {
		return *m.ListMessages
	}
	return false
}

type ClientToServer_DeliverEnvelope struct {
	User             *Byte32 `protobuf:"bytes,3,req,customtype=Byte32" json:"User,omitempty"`
	Envelope         []byte  `protobuf:"bytes,4,req" json:"Envelope,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ClientToServer_DeliverEnvelope) Reset()         { *m = ClientToServer_DeliverEnvelope{} }
func (m *ClientToServer_DeliverEnvelope) String() string { return proto1.CompactTextString(m) }
func (*ClientToServer_DeliverEnvelope) ProtoMessage()    {}

func (m *ClientToServer_DeliverEnvelope) GetEnvelope() []byte {
	if m != nil {
		return m.Envelope
	}
	return nil
}

func init() {
	proto1.RegisterEnum("proto.ServerToClient_StatusCode", ServerToClient_StatusCode_name, ServerToClient_StatusCode_value)
}
