// Code generated by protoc-gen-gogo.
// source: Prekeys.proto
// DO NOT EDIT!

package proto

import testing24 "testing"
import math_rand24 "math/rand"
import time24 "time"
import github_com_gogo_protobuf_proto18 "github.com/gogo/protobuf/proto"
import testing25 "testing"
import math_rand25 "math/rand"
import time25 "time"
import encoding_json6 "encoding/json"
import testing26 "testing"
import math_rand26 "math/rand"
import time26 "time"
import github_com_gogo_protobuf_proto19 "github.com/gogo/protobuf/proto"
import math_rand27 "math/rand"
import time27 "time"
import testing27 "testing"
import github_com_gogo_protobuf_proto20 "github.com/gogo/protobuf/proto"

func TestPrekeysProto(t *testing24.T) {
	popr := math_rand24.New(math_rand24.NewSource(time24.Now().UnixNano()))
	p := NewPopulatedPrekeys(popr, false)
	data, err := github_com_gogo_protobuf_proto18.Marshal(p)
	if err != nil {
		panic(err)
	}
	msg := &Prekeys{}
	if err := github_com_gogo_protobuf_proto18.Unmarshal(data, msg); err != nil {
		panic(err)
	}
	for i := range data {
		data[i] = byte(popr.Intn(256))
	}
	if !p.Equal(msg) {
		t.Fatalf("%#v !Proto %#v", msg, p)
	}
}

func TestPrekeysMarshalTo(t *testing24.T) {
	popr := math_rand24.New(math_rand24.NewSource(time24.Now().UnixNano()))
	p := NewPopulatedPrekeys(popr, false)
	size := p.Size()
	data := make([]byte, size)
	for i := range data {
		data[i] = byte(popr.Intn(256))
	}
	_, err := p.MarshalTo(data)
	if err != nil {
		panic(err)
	}
	msg := &Prekeys{}
	if err := github_com_gogo_protobuf_proto18.Unmarshal(data, msg); err != nil {
		panic(err)
	}
	for i := range data {
		data[i] = byte(popr.Intn(256))
	}
	if !p.Equal(msg) {
		t.Fatalf("%#v !Proto %#v", msg, p)
	}
}

func BenchmarkPrekeysProtoMarshal(b *testing24.B) {
	popr := math_rand24.New(math_rand24.NewSource(616))
	total := 0
	pops := make([]*Prekeys, 10000)
	for i := 0; i < 10000; i++ {
		pops[i] = NewPopulatedPrekeys(popr, false)
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		data, err := github_com_gogo_protobuf_proto18.Marshal(pops[i%10000])
		if err != nil {
			panic(err)
		}
		total += len(data)
	}
	b.SetBytes(int64(total / b.N))
}

func BenchmarkPrekeysProtoUnmarshal(b *testing24.B) {
	popr := math_rand24.New(math_rand24.NewSource(616))
	total := 0
	datas := make([][]byte, 10000)
	for i := 0; i < 10000; i++ {
		data, err := github_com_gogo_protobuf_proto18.Marshal(NewPopulatedPrekeys(popr, false))
		if err != nil {
			panic(err)
		}
		datas[i] = data
	}
	msg := &Prekeys{}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		total += len(datas[i%10000])
		if err := github_com_gogo_protobuf_proto18.Unmarshal(datas[i%10000], msg); err != nil {
			panic(err)
		}
	}
	b.SetBytes(int64(total / b.N))
}

func TestPrekeysJSON(t *testing25.T) {
	popr := math_rand25.New(math_rand25.NewSource(time25.Now().UnixNano()))
	p := NewPopulatedPrekeys(popr, true)
	jsondata, err := encoding_json6.Marshal(p)
	if err != nil {
		panic(err)
	}
	msg := &Prekeys{}
	err = encoding_json6.Unmarshal(jsondata, msg)
	if err != nil {
		panic(err)
	}
	if !p.Equal(msg) {
		t.Fatalf("%#v !Json Equal %#v", msg, p)
	}
}
func TestPrekeysProtoText(t *testing26.T) {
	popr := math_rand26.New(math_rand26.NewSource(time26.Now().UnixNano()))
	p := NewPopulatedPrekeys(popr, true)
	data := github_com_gogo_protobuf_proto19.MarshalTextString(p)
	msg := &Prekeys{}
	if err := github_com_gogo_protobuf_proto19.UnmarshalText(data, msg); err != nil {
		panic(err)
	}
	if !p.Equal(msg) {
		t.Fatalf("%#v !Proto %#v", msg, p)
	}
}

func TestPrekeysProtoCompactText(t *testing26.T) {
	popr := math_rand26.New(math_rand26.NewSource(time26.Now().UnixNano()))
	p := NewPopulatedPrekeys(popr, true)
	data := github_com_gogo_protobuf_proto19.CompactTextString(p)
	msg := &Prekeys{}
	if err := github_com_gogo_protobuf_proto19.UnmarshalText(data, msg); err != nil {
		panic(err)
	}
	if !p.Equal(msg) {
		t.Fatalf("%#v !Proto %#v", msg, p)
	}
}

func TestPrekeysSize(t *testing27.T) {
	popr := math_rand27.New(math_rand27.NewSource(time27.Now().UnixNano()))
	p := NewPopulatedPrekeys(popr, true)
	size2 := github_com_gogo_protobuf_proto20.Size(p)
	data, err := github_com_gogo_protobuf_proto20.Marshal(p)
	if err != nil {
		panic(err)
	}
	size := p.Size()
	if len(data) != size {
		t.Fatalf("size %v != marshalled size %v", size, len(data))
	}
	if size2 != size {
		t.Fatalf("size %v != before marshal proto.Size %v", size, size2)
	}
	size3 := github_com_gogo_protobuf_proto20.Size(p)
	if size3 != size {
		t.Fatalf("size %v != after marshal proto.Size %v", size, size3)
	}
}

func BenchmarkPrekeysSize(b *testing27.B) {
	popr := math_rand27.New(math_rand27.NewSource(616))
	total := 0
	pops := make([]*Prekeys, 1000)
	for i := 0; i < 1000; i++ {
		pops[i] = NewPopulatedPrekeys(popr, false)
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		total += pops[i%1000].Size()
	}
	b.SetBytes(int64(total / b.N))
}

//These tests are generated by github.com/gogo/protobuf/plugin/testgen
